# Generated by Django 3.2 on 2022-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Student', models.CharField(max_length=255)),
                ('CollegeEnrolled', models.CharField(max_length=255)),
                ('Student_Program', models.CharField(max_length=255)),
                ('Date_Of_enrollment', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
